### ISSUE TITLE
Corrected script for proper Modbus RTU over TCP/IP and Modbus TCP/IP

### ISSUE THREAD

**Issue by sebekhtc** [DomoticX/domoticz-modbus#12]
I corrected the script, now Modbus RTU over TCP and Modbus TCP working together with payload decoder.

(I had to add more imports, plus for the Modbus TCP the value was never updated unless it was a coil)

My version:
https://pastebin.com/eQNd7eGm

**Comment by sebekhtc** [comment]
small update:
line 393:            
          Domoticz.Debug("MODBUS DEBUG RESPONSE: " + str(data[0]))
give error: ("Modbus error communicating! (TCP/IP), check your settings!"), but still read the value

replaced with:
         Domoticz.Debug("MODBUS DEBUG RESPONSE: " + str(data))

https://pastebin.com/DUa8x0qC

**Comment by sebekhtc** [comment]
Waiting for the author to accept

**Comment by DomoticX** [comment]
Added/fixed in v1.1.9
