### ISSUE TITLE
Modbus write V1.1.2 - icon is not editable

### ISSUE THREAD

**Issue by Domot** [DomoticX/domoticz-modbus#14]
In modbus-read I can change the icon. In modbus-write I can select another icon but it can't be saved.

**Comment by cezarysz** [comment]
> In modbus-read I can change the icon. In modbus-write I can select another icon but it can't be saved.

It's not caused by script. It must be something in Domoticz DB.

**Comment by DomoticX** [comment]
Maybe this is fixed in Domoticz 2020.2?, not a plugin issue.
