### ISSUE TITLE
modbus TCP - return negative values when the solar system return 0

### ISSUE THREAD

**Issue by pf1979** [DomoticX/domoticz-modbus#15]
I'm using modbus-read (v1.2.0) , to retrieve the power generated by a SMA sunny boy 1.5 inverter with success. However when the power generated is zero (at night for instance), I start having negative values.

Domoticz version: 4.10717
HW Configuration:
<img width="572" alt="HW_config" src="https://user-images.githubusercontent.com/51800741/59463184-4c7d8100-8e1d-11e9-91ec-dcff7894d64b.png">

Screenshot in the end of a production day: (4w)
<img width="397" alt="4W" src="https://user-images.githubusercontent.com/51800741/59463682-7daa8100-8e1e-11e9-9a97-0528713cbf51.png">
<img width="1211" alt="acum" src="https://user-images.githubusercontent.com/51800741/59463683-7daa8100-8e1e-11e9-9fff-e1cb357b66b2.png">

Example when the sensor should be zero:
<img width="397" alt="sensor_negative" src="https://user-images.githubusercontent.com/51800741/59464155-949da300-8e1f-11e9-91a0-7c2dd4e873d7.png">

Graph with generated power:
<img width="1205" alt="Energy_generated graph issue" src="https://user-images.githubusercontent.com/51800741/59464244-d3335d80-8e1f-11e9-9f0d-a64918ad4c83.png">

Do you have an idea something I can adjust? Have you ever been through something similar?

If you need more information, please let me know.
Thanks

**Comment by DomoticX** [comment]
Modbus READ 2020.2A has been released for DomoticZ 2020.2, please try it out if the problem still exist...if yes, please make another topic. closing this one...
