### ISSUE TITLE
Modbus error decoding or received no data (TCP/IP)!, check your settings! SMA

### ISSUE THREAD

**Issue by mike05-1976** [DomoticX/domoticz-modbus#18]
I have a problem with communication.

![modbus instelling](https://user-images.githubusercontent.com/56761476/67145196-a4227200-f27f-11e9-80b5-8fe798d44a4e.png)
![sma gegevens](https://user-images.githubusercontent.com/56761476/67145308-bea91b00-f280-11e9-932e-9a839d2477e4.png)
wat is  it wat i do wrong
ip have no TCP connection 
it works with a smartphone app but not with a raspberry

**Comment by DomoticX** [comment]
Hi There, I think you should use functions 3 “Read holding registers”.

 

Met vriendelijke groet,

 

Sebastiaan Ebeltjes

 

Van: mike05-1976 <notifications@github.com> 
Verzonden: zaterdag 19 oktober 2019 14:58
Aan: DomoticX/domoticz-modbus <domoticz-modbus@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [DomoticX/domoticz-modbus] Modbus error decoding or received no data (TCP/IP)!, check your settings! SMA (#18)

 

I have a problem with communication.

 <https://user-images.githubusercontent.com/56761476/67145196-a4227200-f27f-11e9-80b5-8fe798d44a4e.png> 
 <https://user-images.githubusercontent.com/56761476/67145308-bea91b00-f280-11e9-932e-9a839d2477e4.png> 
wat is it wat i do wrong

**Comment by DomoticX** [comment]
Ok, we have installed domoticz 2020.2 and got modbus working again, we are updating the plugin asap, stay tuned!

**Comment by DomoticX** [comment]
Fixed in update Modbus READ 2020.2A, if not, please make another topic. closing this one...
