### ISSUE TITLE
Modbus read icon not updating.

### ISSUE THREAD

**Issue by bictest** [DomoticX/domoticz-modbus#2]
Hi,

On the read plugin with Modbus TCP/IP.

while changing a value from 0 to 1 the icon is not updating from Off to On.
I tried with register and coil.

I find a way to make it work for me.
First test, Line 126, to be able to see the icon change from On to Off and to be able to change later the Icon type in Domoticz:
Old:if (len(Devices) == 0): Domoticz.Device(Name="ModbusDEV-READ", Unit=1, TypeName="Custom", Image=0, Used=1).Create() # Used=1 to add a switch immediatly!
New:if (len(Devices) == 0): Domoticz.Device(Name="ModbusDEV-READ", Unit=1, TypeName="Switch", Image=0, Used=1).Create() # Used=1 to add a switch immediatly!

next test, on 'pymodbusTCP section' line 307, to have icon works with coil:
Old: Devices[1].Update(0, value) # Update value in Domoticz
New:
if (Parameterq["Username"] == "1") and (value == "1"): Devices[1].Update(1, "1") # Update value in Domoticz
if (Parameterq["Username"] == "1") and (value == "0"): Devices[1].Update(0, "0") # Update value in Domoticz
if (Parameterq["Username"] != "1") and (value == "0"): Devices[1].Update(0, "0") # Update value in Domoticz
if (Parameterq["Username"] == "1") and (value != "0"): Devices[1].Update(1, value) # Update value in Domoticz

**Comment by DomoticX** [comment]
Hi bictest,

I've updated the code, thanks!
