### ISSUE TITLE
Modbus error decoding or received no data (TCP/IP)!, check your settings! Log receive data.

### ISSUE THREAD

**Issue by joep1222** [DomoticX/domoticz-modbus#21]
I have a response from modbus "38"

![image](https://user-images.githubusercontent.com/59375747/71602178-57002d80-2b57-11ea-827f-cb6d3116da89.png)

In devices the status remains 0 .

my settings
![image](https://user-images.githubusercontent.com/59375747/71602199-7008de80-2b57-11ea-9aea-2a7045d28fc1.png)

With modbus poll I have no errors.

**Comment by cezarysz** [comment]
Did you try device address "192.168.1.114"?

pon., 30 gru 2019 o 22:55 joep1222 <notifications@github.com> napisał(a):

**Comment by joep1222** [comment]
Yes, but then domoticz can't find the device.
