### ISSUE TITLE
ModbusRTU slave address issue

### ISSUE THREAD

**Issue by Darek77** [DomoticX/domoticz-modbus#22]
Hi,
I'm using 2 slave devices connected to the same ModbusRTU net. 
First device with address 1 second device with address 70. The first one works fine, Domoticz read registers correctly, but when I want to read registers from second one, domoticz read registers from first one. 
Seems like plug in always read from device address 1 (no matter what RTU address I put there)
I'am using release 2.0.0

![addr](https://user-images.githubusercontent.com/58418398/75588892-d5a31980-5a79-11ea-8245-4e77474c8163.png)

**Comment by DomoticX** [comment]
Try 70/0

**Comment by Darek77** [comment]
70/0 works ok.
thx
I have chacked this with Modbus RTU/ASCII/TCP - WRITE.

**Comment by DomoticX** [comment]
In update Modbus READ 2020.2A, the fields IP:PORT are merged and options working much better now!, closing this one...
