### ISSUE TITLE
ModBus Read - bool type

### ISSUE THREAD

**Issue by Darek77** [DomoticX/domoticz-modbus#23]
Hi
I am working on set up modbus slave I/O module with Domoticz,
No problem with Write Single Coil (Function 5) - bool type
but when I want to Read Discrete Input (Function 2) - there is no option to select Bool type in Data Type parameter.

Is there any option to set up bool type?

I'am using plugin rev 2.0.0

![bool](https://user-images.githubusercontent.com/58418398/75632574-ac12fb00-5bfd-11ea-8e40-c49c8ea2073a.png)

**Comment by DomoticX** [comment]
Added in update Modbus READ 2020.2A, not tested on actual hardware but debug was ok...
