### ISSUE TITLE
float32 swap not works (typo)

### ISSUE THREAD

**Issue by drotos88** [DomoticX/domoticz-modbus#32]
Dear Developer, 
I have found a little typo in modbus-read/plugin.py line 110. The trailing "s" is missing from value:
`                <option label="FLOAT 32-Bit Swapped" value="float32"/>`
It should be:
`                <option label="FLOAT 32-Bit Swapped" value="float32s"/>`
and the swapping will work for 32bit floats as well.

Thanks for your work!

**Comment by DomoticX** [comment]
Hi drotos88, thank you for your input!, we will apply the fix...

**Comment by DomoticX** [comment]
Fixed @ Modbus READ v2021.7
