### ISSUE TITLE
Modbus sensors showing up as Light switch

### ISSUE THREAD

**Issue by thefox154** [DomoticX/domoticz-modbus#4]
When i try to add sensors (hitachi aws-02-mbus & Eastron DSM530mbus)  they show up as a light switch in Domoticz. 

![help with the switches](https://user-images.githubusercontent.com/44209721/47037888-68daf800-d180-11e8-8c39-e7f23e8ef056.jpg)

**Comment by DomoticX** [comment]
Hi thefox154, yes it seems so...some people have giving me tips to update the code, you can revert it by changing switch to custom in this file: https://github.com/DomoticX/domoticz-modbus/commit/127dcbe6d1af3ae2ffe773b4bf62c74c1601ce46#diff-83c76d80ded8d8ab85ec8daeee8d35a1
I am not using domoticz atm so unfortunatly i cannot troubleshoot user input.

**Comment by thefox154** [comment]
Hi sebastiaan,

Super bedankt!!!
Alles werkt nu naar behoren.

Groeten,


Pieter

Van: Sebastiaan Ebeltjes <notifications@github.com>
Verzonden: dinsdag 16 oktober 2018 23:00
Aan: DomoticX/domoticz-modbus <domoticz-modbus@noreply.github.com>
CC: thefox154 <pieter154@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DomoticX/domoticz-modbus] Modbus sensors showing up as Light switch (#4)


Hi thefox154, yes it seems so...some people have giving me tips to update the code, you can revert it by changing switch to custom in this file: 127dcbe#diff-83c76d80ded8d8ab85ec8daeee8d35a1<https://github.com/DomoticX/domoticz-modbus/commit/127dcbe6d1af3ae2ffe773b4bf62c74c1601ce46#diff-83c76d80ded8d8ab85ec8daeee8d35a1>
I am not using domoticz atm so unfortunatly i cannot troubleshoot user input.

**Comment by Sandolution** [comment]
Should be solved with pull request #5

**Comment by DomoticX** [comment]
Fixed in update Modbus READ 2020.2A, you can select sensor type...
