### ISSUE TITLE
TCP Slave ID

### ISSUE THREAD

**Issue by Skulldron** [DomoticX/domoticz-modbus#7]
Hello,
I am wondering if it's possible to choose slave ID in TCPIP method if there are few more modbus slaves with different IDs on one IP adress?
Thanks in advance.

**Comment by PhoenixInteractiveNL** [comment]
Hello Skulldron,

At the moment you can add one IP and ID per "device", i think if you want more you have to add more devices...

**Comment by Skulldron** [comment]
Okay, so here is the screen of config panel:
https://drive.google.com/open?id=1d1RqeC8Tt_gyo41RTjwsUlQ0FiTanW9P

I see device adress entry, where should i enter slave ID?

**Comment by PhoenixInteractiveNL** [comment]
Hello Skulldron,

I now see what you are pointing at, it is not possible at the moment, but i will write some code in the next days to implement it....

**Comment by DomoticX** [comment]
Hello Skulldron,

I have written the code, i cannot test it ATM, can you try it out?
Enter the device ID behind the IP address with a slash, like: 192.168.2.1/56

DL @ pastebin:
READ: https://pastebin.com/nUMnZefu
WRITE: https://pastebin.com/cB9qNM85

**Comment by unto1** [comment]
for modbus Write, it work for me. thanks for this code.

**Comment by sebekhtc** [comment]
I'm trying to get my communication working with Slave ID = 7 on synology dsm but I get:
 2019-02-04 14:35:56.844 Error: (Modbus) failed to load 'plugin.py', Python Path used was '/usr/local/domoticz/var/plugins/modbus-read/:/volume1/@appstore/py3k/usr/local/lib/python35.zip:/volume1/@appstore/py3k/usr/local/lib/python3.5/:/volume1/@appstore/py3k/usr/local/lib/python3.5/plat-linux:/volume1/@appstore/py3k/usr/local/lib/python3.5/lib-dynload'.
2019-02-04 14:35:56.844 Error: (temperature1) Module Import failed, exception: 'TabError'
2019-02-04 14:35:56.844 Error: (temperature1) Import detail: File: /usr/local/domoticz/var/plugins/modbus-read/plugin.py, Line: 248, offset: 64
2019-02-04 14:35:56.844 Error: (temperature1) Error Line ' AddressData = Parameters["Address"].split("/") # Split on "/"
2019-02-04 14:35:56.844 ' 

The previous version had no issue with the python, I could create a device but got no comm as my device is slave id no 7 and  I just got a message
"Modbus error communicating! (RTU/ASCII/RTU over TCP), check your settings!" 

PS. So I found it's an indentation problem. Still trying to find solution as changing tabs to spaces or spaces to tabs is not helping but moving the problem the further lines.
Please advise.

PS.2 I corrected indentation now the script creates the device but no update for yhe value read through Modbus (still "Modbus error communicating! (RTU/ASCII/RTU over TCP), check your settings!").
here is the corrected plugin:
https://pastebin.com/Ycxry3xn

**Comment by PhoenixInteractiveNL** [comment]
Maybe is is the string type in the command....for the read section, can you try changing it to int and try again?:

client = ModbusClient(host=UnitAddress, port=int(Parameters["Port"]), unit_id=UnitIdForIp, auto_open=True, auto_close=True, timeout=5)

into:

client = ModbusClient(host=UnitAddress, port=int(Parameters["Port"]), unit_id=int(UnitIdForIp), auto_open=True, auto_close=True, timeout=5)

Note: unit_id=UnitIdForIp >> unit_id=int(UnitIdForIp)

**Comment by sebekhtc** [comment]
Update: 
Working at site with Modbus communciating devices I took opportunity to troubleshoot the script.
The read from the modbus slave works with the version with corrected intendation (the one I left in pastebin). No need to correct the value reading part. But I get decoding error.
My other problem is having 12 modbus slaves I can only read 3 of them, two of them are Slave ID =1, one is SlaveID=2, that means the UnitID feature works.
Why I can't reach other slaves while my control system can and I can ping them from my Ubuntu with Domoticz  - I have no idea.  (I use the python scripts straight from the linux terminal, troubleshooting ongoing, if I find something I will update the thread, also waiting for suggestion - pure python decoding procedure that I can test from the terminal etc.)

P.S1. part of the log showing proper reading and decoder error:
2019-02-16 12:35:03.928 (test3) MODBUS DEBUG TCP CMD - Method=tcpip, Address=172.16.201.115, Port=502, Unit ID=2, Register=0, Data type=int16
2019-02-16 12:35:03.960 (test3) MODBUS DEBUG RESPONSE: 34150
2019-02-16 12:35:03.960 (test3) Modbus error decoding or recieved no data (TCP/IP)!, check your settings! 
PS2. The connection issue with the rest of the devices is not releated to python. Connections are immediately terminated using the windows based modscan - seems like network problem on the VLAN configuration inside cisco switches. No issue for the script....

**Comment by sebekhtc** [comment]
I did another test this time on Modbus RTU over TCPIP and found to get a reading:
1) require to import:
from pymodbus.transaction import ModbusRtuFramer

2) modify at # pymodbus: RTU over TCP changing the below from:
c = ModbusTcpClient(host=UnitAddress, port=int(Parameters["Port"]), timeout=5)

to:
client = ModbusTcpClient(host=UnitAddress, port=int(Parameters["Port"]), timeout=5, framer=ModbusRtuFramer)

3) modify at  "# pymodbus section" changing the below (4 times for each type of read) from:
if (Parameters["Username"] == "1"): result = c.read_coils(int(Parameters["Password"]), registercount, unit=int(UnitAddress))

to (slave ID must be used not the IP address of the device):

if (Parameters["Username"] == "1"): data = client.read_coils(int(Parameters["Password"]), registercount, unit=int(UnitIdForIp))




Decoder still gives exceptions, not doing that while running similar script straight from terminal.

**Comment by sebekhtc** [comment]
OK found a reason for the decoder, I had to manually install missing components, on DSM synology I had to use:
sudo pip3 install -U pymodbus constants
sudo pip3 install -U pymodbus payload

I also had to install the "serial" that was missing in my Synology DSM unlike to my PC that I use for Domoticz tests:
sudo pip3 install -U pymodbus serial

**Comment by Domot** [comment]
Hello,

When I'm polling my Siemens Logo! modbus TCP port with an universal poller it presents data of two analog input values in the input registers 30001 and 30002 (Function 04).

I have downloaded the plugins to show the data in Domoticz. When polling using the Modbs Domoticz plug-in V1.1.3 it gives an error.

I have followed your examples but the logfile in Domoticz shows: Modbus error decoding or recieved no data (TCP/IP)!, check your settings!

Can you give me any advice in what is going wrong?

Below a chronological graphical overview:
![Modbus polling](https://user-images.githubusercontent.com/34413970/54715440-c6220d80-4b53-11e9-8715-75bf9338b40d.JPG)

![Modbus hardware setting](https://user-images.githubusercontent.com/34413970/54715455-cf12df00-4b53-11e9-8f48-b7d4e82b71e2.JPG)

![Modbus hardware setting list](https://user-images.githubusercontent.com/34413970/54715467-d3d79300-4b53-11e9-9a81-129b9b36001e.JPG)

![Modbus device list](https://user-images.githubusercontent.com/34413970/54715481-df2abe80-4b53-11e9-8529-3fa3edda0511.JPG)

![Modbus logging](https://user-images.githubusercontent.com/34413970/54715489-e3ef7280-4b53-11e9-93a2-85f5b2042782.JPG)

**Comment by Domot** [comment]
My issue has been solved by solution of unto1 (commented on 9 Feb) in Issue modbus TCP cant read value.

Thanks a lot for finding out!

**Comment by jesperrooth** [comment]
> Hello Skulldron,
> 
> I have written the code, i cannot test it ATM, can you try it out?
> Enter the device ID behind the IP address with a slash, like: 192.168.2.1/56
> 
> DL @ pastebin:
> READ: https://pastebin.com/nUMnZefu
> WRITE: https://pastebin.com/cB9qNM85

Hi

Even though I used your public files from https://github.com/DomoticX/domoticz-modbus/ or the files from pastebin above I get error messages from the new device ID / IP.

Error Line ' AddressData = Parameters["Address"].split("/") # Split on "/"

**Comment by DomoticX** [comment]
In update Modbus READ 2020.2A, options IP:PORT have been merged, also option readout is much better now. closing this one...
