### ISSUE TITLE
Polling time

### ISSUE THREAD

**Issue by Zoolu74** [DomoticX/domoticz-modbus#9]
How can I set the polling time? Some devices, such as sensors, thermometers, and similar devices, require a polling time of more than a few seconds. But for various buttons and switches, a poll of several hundred milliseconds is needed.

**Comment by DomoticX** [comment]
More research needed atm....how to add this to the plugin...

**Comment by DomoticX** [comment]
Added pollingrate setting in modbus READ v2020.2B unfortunatly only seconds are supported in domoticz, closing...
